version: 2
sphinx:
  configuration: py-rgrow/docs/source/conf.py
build:
    os: ubuntu-22.04
    tools:
        python: "3.10"
    jobs:
      pre_install:
        - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
        - source $HOME/.cargo/env
python:
  install:
    - method: pip
      path: py-rgrow
      extra_requirements:
        - docs

