version: 2
sphinx:
  configuration: py-rgrow/docs/source/conf.py
build:
    os: ubuntu-22.04
    tools:
        python: "3.10"
        rust: "nightly"
python:
  install:
    - method: pip
      path: py-rgrow
      extra_requirements:
        - docs
